// auto-generated by pencel on 10/27/2025, 7:18:37 PM
declare interface Document {
	createElement(
		tagName: "button",
		options: {
			is: "wb-button";
		},
	): HTMLPenButtonElement;
}
declare interface HTMLButtonElement {
	setAttribute(name: "is", value: "wb-button"): void;
}
declare interface Document {
	createElement(
		tagName: "details",
		options: {
			is: "wb-details";
		},
	): HTMLPenDetailsElement;
}
declare interface HTMLDetailsElement {
	setAttribute(name: "is", value: "wb-details"): void;
}
