# Bun configuration
[install]
production = false

# Path mappings for development - tell Bun to resolve @pencel/* to source files
[run]
# Enable automatic TypeScript compilation and path resolution
tsconfigOverride = "./tsconfig.json"