import type ts from "typescript";

const MARKER_HEADER = "auto-generated by pencel on";
const NEWLINES_SPLIT_REGEXP = /[\r\n]/;

export function createPencelMarker(_sourceFile: ts.SourceFile): string {
  const timestamp = new Date().toLocaleString();
  return `${MARKER_HEADER} ${timestamp}`;
}

export function isPencelGeneratedFile(sourceFile: ts.SourceFile): boolean {
  const text = sourceFile.getFullText().split(NEWLINES_SPLIT_REGEXP, 1)[0];
  return text?.includes(MARKER_HEADER) ?? false;
}
