// ["Generated by Pencel","2025-09-15T18:36:15.077Z","0f94dac185d0a215f77e3335f0d00de8c2eb2d6517dbaab4d0e0199b74e324a4"]
import { Component, Prop, State } from "@pencel/runtime";
@Component({
	tag: "fancy-button",
	styles: ":host {\n  border: 1px solid red;\n}\n",
	styleUrls: {},
})
class FancyButton extends HTMLButtonElement {
	@Prop({ reflect: true })
	isDisabled = false;
	@State()
	isActive: number = 1;
	constructor() {
		super();
	}
	connectedCallback() {
		console.log("Custom button connected!");
	}
}
@Component({ tag: "simple-element", styles: "", styleUrls: {} })
class SimpleElement extends HTMLElement {
	constructor() {
		super();
	}
}
